export const SUGGESTIONS: string[] = [
  // Apple
  "How much cash does Apple actually have right now?",
  "What % of Apple's revenue comes from iPhone?",
  "How fast is Apple's services segment growing?",
  "What did Apple spend on R&D last year?",
  "How much has Apple spent on buybacks in 5 years?",
  "What is Apple's gross margin vs 3 years ago?",
  "How much does Apple make per employee?",
  "What risks did Apple flag in their latest 10-K?",
  "Does Apple carry more debt or cash?",
  "How much did Apple earn in a single day last quarter?",
  "What is Apple's revenue outside the US?",
  "How has Apple's operating income changed over 3 years?",
  "What is Apple's biggest cost of revenue?",
  "How much did Apple pay in taxes last year?",
  "What is Apple's free cash flow trend?",
  "How dependent is Apple on China for revenue?",
  "What did Apple say about AI in their latest filing?",
  "How much did Apple grow wearables revenue?",
  "What is Apple's return on equity?",
  "How much inventory does Apple hold?",

  // Alphabet
  "How much of Alphabet's revenue is just ads?",
  "How fast is Google Cloud growing?",
  "What did Alphabet spend on capital expenditures last year?",
  "How much does Alphabet make from YouTube?",
  "What are Alphabet's biggest disclosed risk factors?",
  "How much cash does Alphabet have on hand?",
  "What is Alphabet's operating margin trend?",
  "How much did Alphabet spend on AI research?",
  "What is Alphabet's headcount vs revenue ratio?",
  "How has Alphabet's net income changed in 3 years?",
  "What % of Alphabet revenue comes from outside the US?",
  "How much did Alphabet pay in stock-based compensation?",
  "What is Alphabet's free cash flow last quarter?",
  "How much did Alphabet invest in Other Bets?",
  "What did Alphabet say about search competition risks?",
  "How much did Google Cloud lose before turning profitable?",
  "What is Alphabet's effective tax rate?",
  "How much did Alphabet spend on buybacks?",
  "What is Alphabet's long-term debt level?",
  "How much did Alphabet earn per share last year?",

  // Amazon
  "What % of Amazon's profit comes from AWS?",
  "How much does Amazon spend on fulfillment per year?",
  "How fast is AWS revenue growing?",
  "What is Amazon's operating margin outside AWS?",
  "How much did Amazon invest in capex last year?",
  "What is Amazon's biggest cost line item?",
  "How much does Amazon make from advertising?",
  "What risks did Amazon highlight in their 10-K?",
  "How much cash does Amazon hold?",
  "How has Amazon's headcount changed in 3 years?",
  "What is Amazon's free cash flow trend?",
  "How much debt does Amazon carry?",
  "What did Amazon say about AI investment plans?",
  "How much did Amazon spend on technology and content?",
  "What is Amazon's net income margin?",
  "How much did Amazon Prime contribute to revenue?",
  "What is Amazon's international revenue trend?",
  "How much did Amazon pay in interest on debt?",
  "What is Amazon's inventory turnover?",
  "How much did Amazon earn from third-party seller services?",

  // Meta
  "How much does Meta make per user per year?",
  "What % of Meta's revenue comes from ads?",
  "How much has Meta spent on the metaverse so far?",
  "What is Meta's operating margin trend?",
  "How much cash does Meta hold?",
  "How much did Meta spend on R&D last year?",
  "What did Meta say about AI in their latest 10-K?",
  "How has Meta's daily active user count changed?",
  "What are Meta's biggest disclosed risk factors?",
  "How much did Meta earn in free cash flow?",
  "What is Meta's headcount after recent layoffs?",
  "How much did Meta spend on stock buybacks?",
  "How much did Reality Labs lose last year?",
  "What is Meta's revenue per employee?",
  "How has Meta's net income changed in 3 years?",
  "What is Meta's long-term debt level?",
  "How much did Meta pay in legal settlements?",
  "What is Meta's effective tax rate?",
  "How fast is Meta's ad revenue growing?",
  "What did Meta say about regulatory risks?",

  // Tesla
  "What is Tesla's gross margin on vehicles?",
  "How much cash does Tesla hold?",
  "How fast is Tesla's energy business growing?",
  "What is Tesla's revenue per vehicle delivered?",
  "How much did Tesla spend on R&D last year?",
  "What risks did Tesla flag in their latest 10-K?",
  "How has Tesla's operating margin changed in 3 years?",
  "How much did Tesla earn from regulatory credits?",
  "What is Tesla's free cash flow trend?",
  "How much does Tesla spend on capex per year?",
  "What did Tesla say about competition risks?",
  "How much debt does Tesla carry?",
  "How has Tesla's vehicle delivery growth trended?",
  "What is Tesla's biggest cost of goods sold?",
  "How much did Tesla make from its services segment?",
  "What is Tesla's net income margin?",
  "How much did Tesla invest in Gigafactory expansion?",
  "What did Tesla say about Full Self-Driving in filings?",
  "How has Tesla's revenue mix shifted over 3 years?",
  "What is Tesla's return on assets?",

  // Microsoft
  "How much of Microsoft's revenue comes from cloud?",
  "How fast is Azure growing vs AWS?",
  "What did Microsoft spend on the Activision acquisition?",
  "How much cash does Microsoft hold?",
  "What is Microsoft's operating margin trend?",
  "How much did Microsoft spend on R&D last year?",
  "What did Microsoft say about AI in their latest 10-K?",
  "How much does Microsoft make from Office 365?",
  "What are Microsoft's biggest disclosed risks?",
  "How much did Microsoft earn in free cash flow?",
  "What is Microsoft's revenue outside the US?",
  "How has Microsoft's headcount changed in 3 years?",
  "What is Microsoft's effective tax rate?",
  "How much did Microsoft pay in dividends last year?",
  "How has Microsoft's net income grown over 5 years?",
  "What is Microsoft's gaming revenue after Activision?",
  "How much long-term debt does Microsoft carry?",
  "What is Microsoft's gross margin by segment?",
  "How much did Microsoft spend on stock buybacks?",
  "What is Microsoft's LinkedIn revenue contribution?",

  // NVIDIA
  "How much did NVIDIA's data center revenue grow last quarter?",
  "What % of NVIDIA's revenue comes from AI chips?",
  "How fast is NVIDIA's revenue growing year over year?",
  "What is NVIDIA's gross margin — and why is it so high?",
  "How much cash does NVIDIA hold?",
  "What did NVIDIA spend on R&D last year?",
  "What risks did NVIDIA flag around China export controls?",
  "How has NVIDIA's gaming revenue changed in 3 years?",
  "What is NVIDIA's free cash flow trend?",
  "How much did NVIDIA earn per share last year?",
  "What is NVIDIA's operating margin vs peers?",
  "How much did NVIDIA spend on stock buybacks?",
  "What did NVIDIA say about supply chain risks?",
  "How has NVIDIA's headcount scaled with revenue?",
  "What is NVIDIA's automotive segment revenue?",
  "How much long-term debt does NVIDIA carry?",
  "What did NVIDIA say about competition in AI chips?",
  "How much did NVIDIA pay in taxes last year?",
  "What is NVIDIA's revenue concentration by customer?",
  "How has NVIDIA's market position changed per their filings?",
];
